2021/05/10 09:28:13 [emerg] 1324#13576: CreateFile() "C:\Users\j1781\Desktop\聚联\nginx - gzfude/conf/nginx.conf" failed (1113: No mapping for the Unicode character exists in the target multi-byte code page)
2021/05/10 09:28:24 [emerg] 2560#13128: CreateFile() "C:\Users\j1781\Desktop\聚联\nginx - gzfude/conf/nginx.conf" failed (1113: No mapping for the Unicode character exists in the target multi-byte code page)
2021/05/10 10:05:11 [emerg] 14396#13576: CreateFile() "C:\Users\j1781\Desktop\聚联\nginx - gzfude/conf/nginx.conf" failed (1113: No mapping for the Unicode character exists in the target multi-byte code page)
2021/05/10 10:05:12 [emerg] 2644#16484: CreateFile() "C:\Users\j1781\Desktop\聚联\nginx - gzfude/conf/nginx.conf" failed (1113: No mapping for the Unicode character exists in the target multi-byte code page)
2021/05/10 10:07:10 [emerg] 5900#4656: CreateFile() "C:\Users\j1781\Desktop\聚联\nginx - gzfude/conf/nginx.conf" failed (1113: No mapping for the Unicode character exists in the target multi-byte code page)
2021/05/10 10:15:17 [emerg] 16568#8144: CreateFile() "C:\Users\j1781\Desktop\聚联\nginx - gzfude/conf/nginx.conf" failed (1113: No mapping for the Unicode character exists in the target multi-byte code page)
2021/05/10 10:38:02 [emerg] 16592#17452: CreateFile() "C:\Users\j1781\Desktop\聚联\nginx - gzfude/conf/nginx.conf" failed (1113: No mapping for the Unicode character exists in the target multi-byte code page)
2021/05/10 10:40:04 [emerg] 10220#12816: CreateFile() "C:\Users\j1781\Desktop\聚联\nginx - gzfude/conf/nginx.conf" failed (1113: No mapping for the Unicode character exists in the target multi-byte code page)
2021/05/10 12:56:40 [error] 8920#17220: *159 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 127.0.0.1, server: pj.xiaomy.net, request: "POST /blade-auth/oauth/token?tenantId=000000&refresh_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJpc3N1c2VyIiwiYXVkIjoiYXVkaWVuY2UiLCJ1c2VyX2lkIjoiMTEyMzU5ODgyMTczODY3NTIwMSIsInRva2VuX3R5cGUiOiJyZWZyZXNoX3Rva2VuIiwiY2xpZW50X2lkIjoic2FiZXIiLCJleHAiOjE2MjEyMjI2MTgsIm5iZiI6MTYyMDYxNzgxOH0.sQJIHEXwPDYXjTfSX7TDMGrql3Ic7bYpAKfnlXDr9gup4YmR9pux0rW2SWHfdlxVN2vKlZFfIMtUqJpA7KwjDQ&grant_type=refresh_token&scope=all HTTP/1.1", upstream: "http://127.0.0.1:89/blade-auth/oauth/token?tenantId=000000&refresh_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJpc3N1c2VyIiwiYXVkIjoiYXVkaWVuY2UiLCJ1c2VyX2lkIjoiMTEyMzU5ODgyMTczODY3NTIwMSIsInRva2VuX3R5cGUiOiJyZWZyZXNoX3Rva2VuIiwiY2xpZW50X2lkIjoic2FiZXIiLCJleHAiOjE2MjEyMjI2MTgsIm5iZiI6MTYyMDYxNzgxOH0.sQJIHEXwPDYXjTfSX7TDMGrql3Ic7bYpAKfnlXDr9gup4YmR9pux0rW2SWHfdlxVN2vKlZFfIMtUqJpA7KwjDQ&grant_type=refresh_token&scope=all", host: "localhost", referrer: "http://localhost:1888/"
2021/05/10 12:56:40 [error] 8920#17220: *161 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 127.0.0.1, server: pj.xiaomy.net, request: "POST /blade-auth/oauth/token?tenantId=000000&refresh_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJpc3N1c2VyIiwiYXVkIjoiYXVkaWVuY2UiLCJ1c2VyX2lkIjoiMTEyMzU5ODgyMTczODY3NTIwMSIsInRva2VuX3R5cGUiOiJyZWZyZXNoX3Rva2VuIiwiY2xpZW50X2lkIjoic2FiZXIiLCJleHAiOjE2MjEyMjI2MTgsIm5iZiI6MTYyMDYxNzgxOH0.sQJIHEXwPDYXjTfSX7TDMGrql3Ic7bYpAKfnlXDr9gup4YmR9pux0rW2SWHfdlxVN2vKlZFfIMtUqJpA7KwjDQ&grant_type=refresh_token&scope=all HTTP/1.1", upstream: "http://127.0.0.1:89/blade-auth/oauth/token?tenantId=000000&refresh_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJpc3N1c2VyIiwiYXVkIjoiYXVkaWVuY2UiLCJ1c2VyX2lkIjoiMTEyMzU5ODgyMTczODY3NTIwMSIsInRva2VuX3R5cGUiOiJyZWZyZXNoX3Rva2VuIiwiY2xpZW50X2lkIjoic2FiZXIiLCJleHAiOjE2MjEyMjI2MTgsIm5iZiI6MTYyMDYxNzgxOH0.sQJIHEXwPDYXjTfSX7TDMGrql3Ic7bYpAKfnlXDr9gup4YmR9pux0rW2SWHfdlxVN2vKlZFfIMtUqJpA7KwjDQ&grant_type=refresh_token&scope=all", host: "localhost", referrer: "http://localhost:1888/"
2021/05/10 12:56:40 [error] 8920#17220: *163 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 127.0.0.1, server: pj.xiaomy.net, request: "POST /blade-auth/oauth/token?tenantId=000000&refresh_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJpc3N1c2VyIiwiYXVkIjoiYXVkaWVuY2UiLCJ1c2VyX2lkIjoiMTEyMzU5ODgyMTczODY3NTIwMSIsInRva2VuX3R5cGUiOiJyZWZyZXNoX3Rva2VuIiwiY2xpZW50X2lkIjoic2FiZXIiLCJleHAiOjE2MjEyMjI2MTgsIm5iZiI6MTYyMDYxNzgxOH0.sQJIHEXwPDYXjTfSX7TDMGrql3Ic7bYpAKfnlXDr9gup4YmR9pux0rW2SWHfdlxVN2vKlZFfIMtUqJpA7KwjDQ&grant_type=refresh_token&scope=all HTTP/1.1", upstream: "http://127.0.0.1:89/blade-auth/oauth/token?tenantId=000000&refresh_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJpc3N1c2VyIiwiYXVkIjoiYXVkaWVuY2UiLCJ1c2VyX2lkIjoiMTEyMzU5ODgyMTczODY3NTIwMSIsInRva2VuX3R5cGUiOiJyZWZyZXNoX3Rva2VuIiwiY2xpZW50X2lkIjoic2FiZXIiLCJleHAiOjE2MjEyMjI2MTgsIm5iZiI6MTYyMDYxNzgxOH0.sQJIHEXwPDYXjTfSX7TDMGrql3Ic7bYpAKfnlXDr9gup4YmR9pux0rW2SWHfdlxVN2vKlZFfIMtUqJpA7KwjDQ&grant_type=refresh_token&scope=all", host: "localhost", referrer: "http://localhost:1888/"
2021/05/10 15:28:36 [error] 8920#17220: *331 CreateFile() "D:/workspace2/gz-proj/gzproj-saber/dist/doc.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: pj.xiaomy.net, request: "GET /doc.html HTTP/1.1", host: "localhost"
2021/05/10 15:28:36 [error] 8920#17220: *331 CreateFile() "D:/workspace2/gz-proj/gzproj-saber/dist/index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: pj.xiaomy.net, request: "GET /doc.html HTTP/1.1", host: "localhost"
2021/05/10 15:28:36 [error] 8920#17220: *332 CreateFile() "D:/workspace2/gz-proj/gzproj-saber/dist/favicon.ico" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: pj.xiaomy.net, request: "GET /favicon.ico HTTP/1.1", host: "localhost"
2021/05/10 15:28:36 [error] 8920#17220: *332 CreateFile() "D:/workspace2/gz-proj/gzproj-saber/dist/index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: pj.xiaomy.net, request: "GET /favicon.ico HTTP/1.1", host: "localhost"
2021/05/10 15:30:08 [error] 8920#17220: *335 CreateFile() "D:/workspace2/gz-proj/gzproj-saber/dist/doc.htm" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: pj.xiaomy.net, request: "GET /doc.htm HTTP/1.1", host: "localhost"
2021/05/10 15:30:08 [error] 8920#17220: *335 CreateFile() "D:/workspace2/gz-proj/gzproj-saber/dist/index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: pj.xiaomy.net, request: "GET /doc.htm HTTP/1.1", host: "localhost"
2021/05/10 15:30:08 [error] 8920#17220: *335 CreateFile() "D:/workspace2/gz-proj/gzproj-saber/dist/favicon.ico" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: pj.xiaomy.net, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/doc.htm"
2021/05/10 15:30:08 [error] 8920#17220: *335 CreateFile() "D:/workspace2/gz-proj/gzproj-saber/dist/index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: pj.xiaomy.net, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/doc.htm"
2021/05/12 09:13:49 [notice] 3352#9984: signal process started
2021/05/12 09:13:49 [error] 3352#9984: OpenEvent("Global\ngx_quit_17012") failed (2: The system cannot find the file specified)
2021/05/12 11:14:15 [notice] 12632#1744: signal process started
2021/05/12 13:33:07 [notice] 14844#8488: signal process started
2021/05/19 13:10:21 [error] 16180#12140: *671 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 127.0.0.1, server: pj.xiaomy.net, request: "POST /blade-auth/oauth/token?tenantId=000000&refresh_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJpc3N1c2VyIiwiYXVkIjoiYXVkaWVuY2UiLCJ1c2VyX2lkIjoiMTEyMzU5ODgyMTczODY3NTIwMSIsInRva2VuX3R5cGUiOiJyZWZyZXNoX3Rva2VuIiwiY2xpZW50X2lkIjoic2FiZXIiLCJleHAiOjE2MjIwMDE0MTQsIm5iZiI6MTYyMTM5NjYxNH0.jmJJU_gKeun5ZD0oHNfjRCl4TOBi5tveObGMeAzaIlOLG8ZFklfHMo4FPBUhaX8pGwN2VzbgweDQ48y905AEXw&grant_type=refresh_token&scope=all HTTP/1.1", upstream: "http://127.0.0.1:89/blade-auth/oauth/token?tenantId=000000&refresh_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJpc3N1c2VyIiwiYXVkIjoiYXVkaWVuY2UiLCJ1c2VyX2lkIjoiMTEyMzU5ODgyMTczODY3NTIwMSIsInRva2VuX3R5cGUiOiJyZWZyZXNoX3Rva2VuIiwiY2xpZW50X2lkIjoic2FiZXIiLCJleHAiOjE2MjIwMDE0MTQsIm5iZiI6MTYyMTM5NjYxNH0.jmJJU_gKeun5ZD0oHNfjRCl4TOBi5tveObGMeAzaIlOLG8ZFklfHMo4FPBUhaX8pGwN2VzbgweDQ48y905AEXw&grant_type=refresh_token&scope=all", host: "localhost", referrer: "http://localhost:1888/"
2021/05/21 14:17:47 [error] 7688#8724: *1487 "D:/workspace2/gz-proj/gzproj-saber/dist/index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: pj.xiaomy.net, request: "GET / HTTP/1.1", host: "www.imomoe.io"
2021/05/21 14:17:47 [error] 7688#8724: *1487 CreateFile() "D:/workspace2/gz-proj/gzproj-saber/dist/index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: pj.xiaomy.net, request: "GET / HTTP/1.1", host: "www.imomoe.io"
2021/05/21 14:17:49 [error] 7688#8724: *1487 "D:/workspace2/gz-proj/gzproj-saber/dist/index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: pj.xiaomy.net, request: "GET / HTTP/1.1", host: "www.imomoe.io"
2021/05/21 14:17:49 [error] 7688#8724: *1487 CreateFile() "D:/workspace2/gz-proj/gzproj-saber/dist/index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: pj.xiaomy.net, request: "GET / HTTP/1.1", host: "www.imomoe.io"
2021/05/24 13:04:49 [error] 19296#1640: *273 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 127.0.0.1, server: pj.xiaomy.net, request: "POST /blade-auth/oauth/token?tenantId=000000&refresh_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJpc3N1c2VyIiwiYXVkIjoiYXVkaWVuY2UiLCJ1c2VyX2lkIjoiMTEyMzU5ODgyMTczODY3NTIwMSIsInRva2VuX3R5cGUiOiJyZWZyZXNoX3Rva2VuIiwiY2xpZW50X2lkIjoic2FiZXIiLCJleHAiOjE2MjI0MzMwNTYsIm5iZiI6MTYyMTgyODI1Nn0.xUAig_6Nyydt23HMJjo2rRr5fAelpxmC8vRQ9NSes4j0QHUgZDEmn5iNiFlnCkM1q9yAxqlpxbilkTcCKX0NuA&grant_type=refresh_token&scope=all HTTP/1.1", upstream: "http://127.0.0.1:89/blade-auth/oauth/token?tenantId=000000&refresh_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJpc3N1c2VyIiwiYXVkIjoiYXVkaWVuY2UiLCJ1c2VyX2lkIjoiMTEyMzU5ODgyMTczODY3NTIwMSIsInRva2VuX3R5cGUiOiJyZWZyZXNoX3Rva2VuIiwiY2xpZW50X2lkIjoic2FiZXIiLCJleHAiOjE2MjI0MzMwNTYsIm5iZiI6MTYyMTgyODI1Nn0.xUAig_6Nyydt23HMJjo2rRr5fAelpxmC8vRQ9NSes4j0QHUgZDEmn5iNiFlnCkM1q9yAxqlpxbilkTcCKX0NuA&grant_type=refresh_token&scope=all", host: "localhost", referrer: "http://localhost:1888/"
2021/05/24 13:14:15 [notice] 13336#15932: signal process started
2021/05/24 15:09:06 [notice] 18228#768: signal process started
2021/05/25 13:22:32 [notice] 21136#22264: signal process started
2021/05/25 15:25:00 [error] 21444#8404: *141 "D:/workspace2/gz-proj/gzproj-saber/dist/index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: pj.xiaomy.net, request: "GET / HTTP/1.1", host: "www.imomoe.io"
2021/05/25 15:25:00 [error] 21444#8404: *141 CreateFile() "D:/workspace2/gz-proj/gzproj-saber/dist/index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: pj.xiaomy.net, request: "GET / HTTP/1.1", host: "www.imomoe.io"
2021/05/25 15:25:01 [error] 21444#8404: *141 "D:/workspace2/gz-proj/gzproj-saber/dist/index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: pj.xiaomy.net, request: "GET / HTTP/1.1", host: "www.imomoe.io"
2021/05/25 15:25:01 [error] 21444#8404: *141 CreateFile() "D:/workspace2/gz-proj/gzproj-saber/dist/index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: pj.xiaomy.net, request: "GET / HTTP/1.1", host: "www.imomoe.io"
2021/05/25 16:20:48 [notice] 11924#14200: signal process started
2021/05/25 16:21:01 [notice] 11220#8128: signal process started
2021/05/25 16:21:01 [error] 11220#8128: CreateFile() "C:\Users\j1781\Desktop\julian\fude\nginx - gzfude/logs/nginx.pid" failed (2: The system cannot find the file specified)
2021/06/04 13:00:49 [error] 15244#11644: *75 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 127.0.0.1, server: pj.xiaomy.net, request: "POST /blade-auth/oauth/token?tenantId=000000&refresh_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJpc3N1c2VyIiwiYXVkIjoiYXVkaWVuY2UiLCJ1c2VyX2lkIjoiMTEyMzU5ODgyMTczODY3NTIwMSIsInRva2VuX3R5cGUiOiJyZWZyZXNoX3Rva2VuIiwiY2xpZW50X2lkIjoic2FiZXIiLCJleHAiOjE2MjMzODEzNjAsIm5iZiI6MTYyMjc3NjU2MH0.CyKsCurLVbmZlz3BZ8ZETC-zbtOQZccZzcZG0QXz2kKt_3NsTEZx9lCBdtgQu5FuA4CrsxEcK5cnCp-7W46X-A&grant_type=refresh_token&scope=all HTTP/1.1", upstream: "http://127.0.0.1:89/blade-auth/oauth/token?tenantId=000000&refresh_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJpc3N1c2VyIiwiYXVkIjoiYXVkaWVuY2UiLCJ1c2VyX2lkIjoiMTEyMzU5ODgyMTczODY3NTIwMSIsInRva2VuX3R5cGUiOiJyZWZyZXNoX3Rva2VuIiwiY2xpZW50X2lkIjoic2FiZXIiLCJleHAiOjE2MjMzODEzNjAsIm5iZiI6MTYyMjc3NjU2MH0.CyKsCurLVbmZlz3BZ8ZETC-zbtOQZccZzcZG0QXz2kKt_3NsTEZx9lCBdtgQu5FuA4CrsxEcK5cnCp-7W46X-A&grant_type=refresh_token&scope=all", host: "localhost", referrer: "http://localhost:1888/"
2021/06/23 16:35:13 [notice] 13132#15476: signal process started
2021/06/24 10:49:59 [error] 23584#18232: *937 CreateFile() "D:/workspace2/gz-proj/gzproj-saber/dist/favicon.ico" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: pj.xiaomy.net, request: "GET /favicon.ico HTTP/1.1", host: "www.imomoe.io"
2021/06/24 10:49:59 [error] 23584#18232: *937 CreateFile() "D:/workspace2/gz-proj/gzproj-saber/dist/index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: pj.xiaomy.net, request: "GET /favicon.ico HTTP/1.1", host: "www.imomoe.io"
2021/06/24 13:52:19 [error] 23584#18232: *1716 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: pj.xiaomy.net, request: "GET /blade-system/dept/tree HTTP/1.1", upstream: "http://127.0.0.1:88/blade-system/dept/tree", host: "localhost", referrer: "http://localhost:1888/"
2021/06/24 13:52:19 [error] 23584#18232: *1726 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: pj.xiaomy.net, request: "GET /blade-emp/empemployee/list?types=1&current=1&size=10 HTTP/1.1", upstream: "http://127.0.0.1:88/blade-emp/empemployee/list?types=1&current=1&size=10", host: "localhost", referrer: "http://localhost:1888/"
2021/06/24 13:52:19 [error] 23584#18232: *1718 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: pj.xiaomy.net, request: "GET /blade-system/dict-biz/dictionary?code=WORK_TYPE HTTP/1.1", upstream: "http://127.0.0.1:88/blade-system/dict-biz/dictionary?code=WORK_TYPE", host: "localhost", referrer: "http://localhost:1888/"
2021/06/24 13:52:19 [error] 23584#18232: *1720 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: pj.xiaomy.net, request: "GET /blade-system/dict/dictionary?code=nationality HTTP/1.1", upstream: "http://127.0.0.1:88/blade-system/dict/dictionary?code=nationality", host: "localhost", referrer: "http://localhost:1888/"
2021/06/24 13:52:19 [error] 23584#18232: *1719 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: pj.xiaomy.net, request: "GET /blade-system/role/tree?tenantId=000000 HTTP/1.1", upstream: "http://127.0.0.1:88/blade-system/role/tree?tenantId=000000", host: "localhost", referrer: "http://localhost:1888/"
2021/06/24 13:52:19 [error] 23584#18232: *1723 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: pj.xiaomy.net, request: "GET /blade-emp/acsDevice/list HTTP/1.1", upstream: "http://127.0.0.1:88/blade-emp/acsDevice/list", host: "localhost", referrer: "http://localhost:1888/"
2021/06/30 08:58:04 [notice] 14772#4216: signal process started
2021/06/30 09:00:19 [notice] 32796#22812: signal process started
2021/06/30 09:01:25 [notice] 7468#21152: signal process started
